name:                purification
version:             1.0
github:              "riverlane/post-selection-free-purification"
license:             "LicenseRef-MIT-plus-Commons-Clause"
copyright:           "2022 Riverlane Ltd"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/riverlane/post-selection-free-purification>

dependencies:
- base >= 4.7 && < 5
- containers
- multiset
- array

library:
  source-dirs: src

executables:
  purification-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -rtsopts
    dependencies:
    - purification
